Run *all* news scrapers, even if one fails
This ports the changes to the data scrapers from #118 over to the news scrapers, adds slightly nicer formatting, and includes a stack trace. The main thing is that an exception in any scraper does not stop the others from completing. Output-wise, if the Alameda scraper failed, you'd see something like:

    Alameda county failed: 'NoneType' object has no attribute 'find_all'
    Traceback (most recent call last):
    File "scraper_news.py", line 83, in main
        run_county_news(county, from_, format, output)
    File "scraper_news.py", line 40, in run_county_news
        feed = news.scrapers[county].get_news(from_date=from_)
    File "/Users/rbrackett/Dev/sfbrigade/data-covid19-sfbayarea/covid19_sfbayarea/news/base.py", line 80, in get_news
        return instance.scrape()
    File "/Users/rbrackett/Dev/sfbrigade/data-covid19-sfbayarea/covid19_sfbayarea/news/base.py", line 58, in scrape
        news = self.parse_page(html, self.URL)
    File "/Users/rbrackett/Dev/sfbrigade/data-covid19-sfbayarea/covid19_sfbayarea/news/alameda.py", line 78, in parse_page
        article_starts = soup.select_one('#mainCols').find_all('strong')
    AttributeError: 'NoneType' object has no attribute 'find_all'